image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Run Selenium in Docker
        script:
          - docker build -t chrome-selenium .
          - docker run -e DISPLAY=:99 -v $PWD:/tests chrome-selenium pytest --html=report.html tests/
        artifacts:
          - report.html
          - screenshot.png
