image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Build Docker image & run Selenium test
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -t selenium-test-image .
          - docker run --rm \
              -v $(pwd):/tests \
              -w /tests \
              selenium-test-image \
              pytest --html=report.html tests/
        artifacts:
          - report.html
          - screenshot.png
          - main_slot.html